version: '3.8'

services:
  symfony_db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'user'
    ports:
      - 3333:3306
    container_name: sf_db
    networks:
      - symfony_rest

  symfony_web:
    build:
      context: .docker-config/web
    volumes:
      - '.:/var/www/html'
      - './.docker-config/web/vhost.conf:/etc/apache2/sites-available/000-default.conf'
    ports:
      - 8888:80
    container_name: sf_web
    networks:
      - symfony_rest

  symfony_adminer:
    image: adminer
    ports:
      - 9999:8080
    container_name: sf_adm
    networks:
      - symfony_rest

networks:
  symfony_rest:
    name: symfony_rest