controllers:
    resource: ../../src/Controller/Api
    type: annotation
    prefix:   /
    name_prefix: api_
    defaults:
        _format: json

kernel:
    resource: ../../src/Kernel.php
    type: annotation
